repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.4.4 # ğŸ†• è«‹ç”¨æœ€æ–°çš„ Ruff tagï¼šhttps://github.com/astral-sh/ruff/releases
      hooks:
          - id: ruff
            args: [--fix] # è‡ªå‹•ä¿®å¾©ï¼šåŒ…å« pyupgradeã€isortã€æ ¼å¼éŒ¯èª¤ç­‰

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
